#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
	local enabled
	config_load feiyoung
	config_get_bool enabled general enabled 0
	
	if [ "$enabled" -eq 1 ]; then
		procd_open_instance
		procd_set_param command /usr/bin/feiyoung.sh
		procd_set_param respawn
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_close_instance
	fi
}

service_triggers() {
	procd_add_reload_trigger "feiyoung"
}
